image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - chmod +x gradlew
<<<<<<< HEAD
  - ./gradlew test --info
=======
  - ./gradlew test --info 
>>>>>>> 2a9ecbe395d7ed6de446333fea0645d5a44a7b16
